//! Relay runtime assembly and lifecycle (MED-16).
//!
//! Owns the two servers (loopback control plane, LAN media plane), the
//! fetcher composition (MP4 + HLS), a bounded in-flight limit on the media
//! plane (RL-012) and every revocation trigger (RL-004/RL-005): navigation,
//! route lost, device replaced, profile destroyed, app exit. `stop` is
//! idempotent and shuts down in reverse order (servers → sessions → vault).

use crate::hls::stream::HlsFetcher;
use crate::mp4::Mp4Fetcher;
use crate::network_guard::{NetworkGuard, NetworkGuardConfig};
use crate::router::{
    control_router, media_router, FetchError, FetchPlan, FetchRequest, FetchedMedia, RelayCore,
    ResourceFetcher, RouteKind,
};
use crate::session::RevokeReason;
use axum::extract::{Request, State};
use axum::middleware::Next;
use axum::response::{IntoResponse, Response};
use crayon_domain::DeviceId;
use std::future::Future;
use std::net::SocketAddr;
use std::pin::Pin;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::{Arc, Mutex};
use tokio::sync::Semaphore;
use tokio::task::JoinHandle;

/// Default in-flight media request bound (RL-012).
pub const DEFAULT_MAX_CONCURRENT_MEDIA: usize = 64;

/// Runtime configuration.
pub struct RelayRuntimeConfig {
    /// Media plane bind host (`0.0.0.0` for LAN receivers; `127.0.0.1` in tests).
    pub media_host: String,
    /// Media plane port; 0 = system-assigned.
    pub media_port: u16,
    /// Control plane port (loopback); 0 = system-assigned.
    pub control_port: u16,
    /// Per-process control-plane secret (generated by the browser process).
    pub control_secret: String,
    pub max_concurrent_media: usize,
    /// Test hook: allow loopback/private upstreams (local fixtures).
    pub allow_private_upstreams: bool,
    /// Test hook: logical clock override.
    pub now: Option<Arc<dyn Fn() -> u64 + Send + Sync>>,
}

impl Default for RelayRuntimeConfig {
    fn default() -> Self {
        Self {
            media_host: "0.0.0.0".to_string(),
            media_port: 0,
            control_port: 0,
            control_secret: String::new(),
            max_concurrent_media: DEFAULT_MAX_CONCURRENT_MEDIA,
            allow_private_upstreams: false,
            now: None,
        }
    }
}

/// MP4/HLS fetcher composition. DASH relay serving is out of v1 scope.
struct CompositeFetcher {
    mp4: Mp4Fetcher,
    hls: Arc<HlsFetcher>,
}

impl ResourceFetcher for CompositeFetcher {
    fn fetch(
        &self,
        kind: RouteKind,
        plan: FetchPlan,
        request: FetchRequest,
    ) -> Pin<Box<dyn Future<Output = Result<FetchedMedia, FetchError>> + Send>> {
        match kind {
            RouteKind::MasterPlaylist => self.hls.fetch(kind, plan, request),
            RouteKind::DashManifest => Box::pin(async { Err(FetchError::NotFound) }),
            RouteKind::Resource => {
                // MP4 资源走 MP4 链路；其余（.ts/.m4s/嵌套列表）走 HLS 链路
                //（其二进制路径同样是字节直通）。
                let is_mp4 = plan.url.split('?').next().unwrap_or("").ends_with(".mp4");
                if is_mp4 {
                    self.mp4.fetch(kind, plan, request)
                } else {
                    self.hls.fetch(kind, plan, request)
                }
            }
        }
    }
}

struct Servers {
    media: JoinHandle<()>,
    control: JoinHandle<()>,
    shutdown: Arc<tokio::sync::Notify>,
}

/// Running relay. Construct via `RelayRuntime::start`.
pub struct RelayRuntime {
    core: Arc<RelayCore>,
    media_addr: SocketAddr,
    control_addr: SocketAddr,
    servers: Mutex<Option<Servers>>,
    stopped: AtomicBool,
}

impl RelayRuntime {
    /// Assembles and starts both planes.
    pub async fn start(config: RelayRuntimeConfig) -> std::io::Result<Arc<Self>> {
        let now: Arc<dyn Fn() -> u64 + Send + Sync> = config.now.unwrap_or_else(|| {
            Arc::new(|| {
                std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .map(|d| d.as_millis() as u64)
                    .unwrap_or(0)
            })
        });
        let guard = NetworkGuard::new(NetworkGuardConfig {
            allow_private_addresses: config.allow_private_upstreams,
            ..NetworkGuardConfig::default()
        });
        let mp4 = Mp4Fetcher::new(guard.clone());
        let hls = Arc::new(HlsFetcher::new(guard));
        let composite = Arc::new(CompositeFetcher {
            mp4,
            hls: hls.clone(),
        });
        let core = Arc::new(
            RelayCore::new(now)
                .with_control_secret(config.control_secret)
                .with_fetcher(composite),
        );
        hls.bind(&core);

        let shutdown = Arc::new(tokio::sync::Notify::new());
        let media_listener =
            tokio::net::TcpListener::bind((config.media_host.as_str(), config.media_port)).await?;
        let control_listener =
            tokio::net::TcpListener::bind(("127.0.0.1", config.control_port)).await?;
        let media_addr = media_listener.local_addr()?;
        let control_addr = control_listener.local_addr()?;

        let semaphore = Arc::new(Semaphore::new(config.max_concurrent_media));
        let media_app = media_router(core.clone()).layer(axum::middleware::from_fn_with_state(
            semaphore,
            concurrency_gate,
        ));
        let control_app = control_router(core.clone());

        let media_shutdown = shutdown.clone();
        let media = tokio::spawn(async move {
            let _ = axum::serve(
                media_listener,
                media_app.into_make_service_with_connect_info::<SocketAddr>(),
            )
            .with_graceful_shutdown(async move { media_shutdown.notified().await })
            .await;
        });
        let control_shutdown = shutdown.clone();
        let control = tokio::spawn(async move {
            let _ = axum::serve(
                control_listener,
                control_app.into_make_service_with_connect_info::<SocketAddr>(),
            )
            .with_graceful_shutdown(async move { control_shutdown.notified().await })
            .await;
        });

        Ok(Arc::new(Self {
            core,
            media_addr,
            control_addr,
            servers: Mutex::new(Some(Servers {
                media,
                control,
                shutdown,
            })),
            stopped: AtomicBool::new(false),
        }))
    }

    /// Media plane base URL (receivers fetch from this address).
    #[must_use]
    pub fn media_base_url(&self) -> String {
        format!("http://{}", self.media_addr)
    }

    /// Control plane base URL (loopback).
    #[must_use]
    pub fn control_base_url(&self) -> String {
        format!("http://{}", self.control_addr)
    }

    /// Shared core (orchestration layer registers recipes via this handle).
    #[must_use]
    pub fn core(&self) -> &Arc<RelayCore> {
        &self.core
    }

    /// Lifecycle trigger (RL-005): revokes sessions and purges their recipes.
    pub fn trigger(&self, reason: RevokeReason, receiver: Option<&DeviceId>) -> usize {
        let removed = self.core.registry.lock().unwrap().revoke(reason, receiver);
        let mut vault = self.core.vault.lock().unwrap();
        let count = removed.len();
        for session in &removed {
            vault.revoke_session(session);
        }
        count
    }

    /// Idempotent shutdown: servers stop (graceful), then every session and
    /// recipe is revoked. Safe to call twice.
    pub async fn stop(&self) {
        if self.stopped.swap(true, Ordering::SeqCst) {
            return;
        }
        let servers = self.servers.lock().unwrap().take();
        if let Some(servers) = servers {
            servers.shutdown.notify_waiters();
            let _ = servers.media.await;
            let _ = servers.control.await;
        }
        self.trigger(RevokeReason::AppExit, None);
    }
}

/// Bounded in-flight gate for the media plane (RL-012): excess requests get
/// an immediate bounded rejection instead of an unbounded queue. The permit
/// is held by the response body stream, so slow/stalled streams keep
/// occupying their slot until they end or disconnect.
async fn concurrency_gate(
    State(semaphore): State<Arc<Semaphore>>,
    request: Request,
    next: Next,
) -> Response {
    let Ok(permit) = semaphore.clone().try_acquire_owned() else {
        return (
            axum::http::StatusCode::SERVICE_UNAVAILABLE,
            axum::Json(serde_json::json!({ "error": "capacity_exceeded" })),
        )
            .into_response();
    };
    let response = next.run(request).await;
    let (parts, body) = response.into_parts();
    use futures_util::StreamExt;
    let guarded = body.into_data_stream().map(move |item| {
        let _ = &permit; // permit 随流结束/断开释放
        item
    });
    Response::from_parts(parts, axum::body::Body::from_stream(guarded))
}
